

PROMPT CREANDO TABLAS
@@01_TABLA/01_CREACIONTABLAS.sql

PROMPT CREANDO COMENTARIOS
@@01_TABLA/02_COMENTARIOSTABLAS.sql

PROMPT CREANDO SECUENCIAS
@@02_SECUENCIAS/01_SECUENCIAS.sql

PROMPT CREANDO CLAVES PRIMARIAS
@@05_FOREIGN_KEY/01_ClAVESPRIMARIA.sql

PROMPT CREANDO CLAVES FORANEAS
@@05_FOREIGN_KEY/02_CLAVESFORANEAS.sql

PROMPT CREANDO PAQUETE INSERTAR DATOS PERSONA
@@10_PAQUETES/01_PQ_INSERTAR_DATOS.sql

PROMPT CREANDO PAQUETE INSERTAR DATOS USUARIO
@@10_PAQUETES/03_PQ_INSERTAR_DATOS_USUARIOS.sql


PROMPT CREANDO PAQUETE INGRESO
@@10_PAQUETES/05_PQ_INGRESO.sql


PROMPT CREANDO PAQUETE ORQUESTADOR
@@10_PAQUETES/06_PQ_ORQUESTADOR.sql


