

PROMPT CREANDO TABLAS
@@01_TABLA/01_CREACIONTABLAS.sql

PROMPT CREANDO COMENTARIOS
@@01_TABLA/05_COMENTARIOSTABLAS.sql

PROMPT CREANDO SECUENCIAS
@@02_SECUENCIAS/01_SECUENCIAS.sql

PROMPT CREANDO CLAVES PRIMARIAS
@@05_FOREIGN_KEY/01_ClAVESPRIMARIA.sql

PROMPT CREANDO CLAVES FORANEAS
@@05_FOREIGN_KEY/02_CLAVESFORANEAS.sql


